In [1]:
from CartPoleContinuous import ContinuousCartPoleEnv
import numpy as np

In [2]:
env = ContinuousCartPoleEnv()
state = env.reset()
print(state)

[-0.02034118 -0.02601421 -0.0010031  -0.03378912]


/home/jdufou1/.local/lib/python3.8/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [8]:
print(env.action_space)
print(env.observation_space)

Box(-1.0, 1.0, (1,), float32)
Box(-3.4028234663852886e+38, 3.4028234663852886e+38, (4,), float32)


In [4]:
done = False
state = env.reset()
while not done : 
    new_state,reward,done,_ = env.step(np.array([0.5]))
    print(new_state,reward,done)
    state = new_state

[ 0.00382824  0.33195285 -0.01699854 -0.45774981] 1.0 False
[ 0.0104673   0.62486985 -0.02615354 -0.90205916] 1.0 False
[ 0.0229647   0.91789226 -0.04419472 -1.34913073] 1.0 False
[ 0.04132254  1.21108785 -0.07117733 -1.80148371] 1.0 False
[ 0.0655443   1.50445438 -0.10720701 -2.26132775] 1.0 False
[ 0.09563339  1.79788342 -0.15243356 -2.73040289] 1.0 False
[ 0.13159106  2.09111965 -0.20704162 -3.20979901] 1.0 False
[ 0.17341345  2.38371677 -0.2712376  -3.69975763] -1.0 True
